name: scan
on:
  pull_request:
    branches:
      - main
      - staging
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Scan for secrets
        uses: edplato/trufflehog-actions-scan@master
